### ISSUE TITLE
index.html page

### ISSUE THREAD

**Issue by KartikKannapur** [GSC-RNSIT/Campus-Connect#1]
Create an index.html page for your website, on the gh-pages branch.

**Comment by NiranjanBalasubramani** [comment]
Hello Kartik,
I have just created the gh-pages branch. The whole folder is present in the gh-pages branch as well. But am a bit confused to create an index file in the gh-pages branch and a bit overwhelmed with the information present online. I could surely use some help!

**Comment by KartikKannapur** [comment]
@Niranjanabram Just create a file named index.html in the gh-pages branch. You can refer to this repo for more information -  https://github.com/KartikKannapur/MyFirstGithubRepo

**Comment by KartikKannapur** [comment]
Great job on creating the index.html page. I am closing this issue.
